name: HOPR Workflow
on: [push, pull_request]

jobs:
  build:
    name: Build, Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ matrix.node-version }}-build-${{ hashFiles(env.pkgPath) }}
      - name: Install node modules
        working-directory: ${{ env.workDir }}
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
      - name: Build library
        working-directory: ${{ env.workDir }}
        run: |
          yarn build
      - name: Test library
        working-directory: ${{ env.workDir }}
        run: |
          yarn test

  publish_core_npm:
    name: Publish (NPM)

    if: github.event_name == 'push' && github_ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/merge-release@v4.0.7
