on:
  push:
    branches:
      - 'feature/**'
    tags:
      - 'v*'
  pull_request:
    branches: [master, develop]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.9.1]
        yarn-version: [1.19.2]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles(env.pkgPath) }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node modules
        working-directory: ${{ env.workDir }}
        if: steps.cache-modules.outputs.cache-hit != 'true' && steps.filter.outputs[matrix.repository] == 'true'
        run: |
          yarn policies set-version ${{ matrix.yarn-version }}
          yarn install --frozen-lockfile
      - name: Build library
        working-directory: ${{ env.workDir }}
        if: steps.filter.outputs[matrix.repository] == 'true'
        run: |
          yarn policies set-version ${{ matrix.yarn-version }}
          yarn build
      - name: Test library
        working-directory: ${{ env.workDir }}
        if: steps.filter.outputs[matrix.repository] == 'true'
        run: |
          yarn policies set-version ${{ matrix.yarn-version }}
          yarn test

  publish_core_npm:
    if: startsWith(github.ref, 'refs/tags/')

    name: Publish (NPM)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.9.1
          registry-url: https://registry.npmjs.org/
      - name: Get version tag
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}
      - name: Delete version tag
        run: git push --delete origin ${{ steps.get_version.outputs.version }}
      - name: Publish to NPM Registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn policies set-version 1.19.2
          np ${{ steps.get_version.outputs.version}} --access public